---
# Plugin by iSoftMC Team
# Developed by TheAz928
#Config for WelcomeMessae 

message: Welcome, {player}!

# Follow me on Twitter @TheAz928 , Thanks!
# Keep an eye on latest updates! Github.com\iSoftMC\WelcomeMessage
...
